### ISSUE TITLE
Structure code as an R package

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/superwell#10]
Hey, team, I noticed that the code for this project is in an R script at the top level of the repository.  Is there any chance I could talk you guys into structuring the code as an R package?  Making it a package would make it a lot easier for prospective users to install it, and it also allows you to more easily manage dependencies on other packages.  Also, when you install a package, the code goes into a discoverable location, which is a feature that our model coupling code uses to find the code that implements its components.  Finally, R packages have a very nice documentation system that you could take advantage of if you were to package the code.

**Comment by crvernon** [comment]
This is the intent.  We are just getting the initial working version archived, with it's outputs recorded for testing, from a previous effort.  Next steps are to drastically overhaul this codebase.
