### ISSUE TITLE
Re-scope and document functions

### ISSUE THREAD

**Issue by crvernon** [JGCRI/superwell#18]
The original script needs to be scoped to single purpose functions that are correctly documented.

**Comment by hassaniazi** [comment]
This commit along with multiple downstream commits have improved the documentation of the functions. [https://github.com/JGCRI/superwell/commit/19e8ff78cb5d7c332d2f15f849f4bbffb00356b8](19e8ff78cb5d7c332d2f15f849f4bbffb00356b8). `roxygen2` would be rerun again at the end
