### ISSUE TITLE
Replace hard-coded values

### ISSUE THREAD

**Issue by crvernon** [JGCRI/superwell#19]
Replace hard-coded values with variable names within the code.  We will want to be able to manipulate these values without having to reach into the functions that use them.

**Comment by hassaniazi** [comment]
This has been addressed to some extent in these commits [https://github.com/JGCRI/superwell/commit/71cc2c98f987148ba7a87a2957f8121160eee4a9](71cc2c98f987148ba7a87a2957f8121160eee4a9) and [https://github.com/JGCRI/superwell/commit/e27712e42c3875901670b6a21220313631e57ed5](e27712e42c3875901670b6a21220313631e57ed5)
