### ISSUE TITLE
Update to revised source code

### ISSUE THREAD

**Issue by crvernon** [JGCRI/superwell#4]
Update working code as it is currently represented from `/connie-1/projects/JGCRI_YONK/JGCRI/DJ_Share/R Code/MENA_Results_161216/updatedformat/5/superwell.R`

**Comment by nkholod** [comment]
updated to 'MENA_Results_161216/updatedformat/5/superwell.R'

**Comment by crvernon** [comment]
@nkholod Please post what Pull Request resolved this.
